SKILLS = [
    "python",
    "java",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "next.js",
    "nextjs",
    "vue",
    "angular",
    "node.js",
    "nodejs",
    "express",
    "nestjs",
    "php",
    "laravel",
    "codeigniter",
    "golang",
    "c#",
    "c++",
    "swift",
    "kotlin",
    "tailwind",
    "bootstrap",
    "mysql",
    "postgresql",
    "mongodb",
    "sql",
    "redis",
    "graphql",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "firebase",
    "git",
    "github",
    "linux",
    "rest api",
    "excel",
    "power bi",
    "tableau",
    "tensorflow",
    "pytorch",
    "machine learning",
    "data analysis",
    "statistics",
    "figma",
    "photoshop",
    "illustrator",
    "seo",
    "sem",
    "google ads",
    "meta ads",
    "powerpoint",
    "word",
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "collaboration",
    "negotiation",
    "bgp",
    "cisco",
    "cisco asa",
    "cisco nexus",
    "cisco routers",
    "compliance auditing",
    "cryptography",
    "dns",
    "dhcp",
    "eigrp",
    "f5 load balancer",
    "firewalls",
    "firewall management",
    "firewall basics",
    "ids/ips",
    "incident management",
    "lan/wan",
    "malware analysis",
    "mpls",
    "nagios",
    "network monitoring",
    "network troubleshooting",
    "ospf",
    "qos",
    "routing basics",
    "siem tools",
    "sip",
    "soc operations",
    "solarwinds",
    "tcp/ip",
    "threat hunting",
    "voip",
    "vpn",
    "vpn setup"
]
